const CASES = [
  {id:'mcminnville',year:'1950',place:'McMinnville, Oregon',title:'The Trent photographs',tag:'PHOTOGRAPHY',level:'Guided',synopsis:'Two photographs place a dark disc below utility wires. Competing analyses disagree over whether geometry and shadows favor a distant object or a small suspended model.',question:'What can fixed references in two photographs establish about scale and distance?',records:[
    {id:'mc-photo-a',type:'image',date:'11 MAY 1950',title:'Trent photograph — plate 23',source:'Condon case-file reproduction',asset:'assets/mcminnville-1.jpg',note:'One of two exposures. Utility wires and a building edge provide fixed scene references.'},
    {id:'mc-photo-b',type:'image',date:'11 MAY 1950',title:'Trent photograph — plate 24',source:'Condon case-file reproduction',asset:'assets/mcminnville-2.jpg',note:'The second exposure changes object position and camera framing.'},
    {id:'mc-condon',type:'document',date:'1968',title:'Condon Report, Case 46',source:'University of Colorado study; NCAS copy',note:'Photographic case study examining witness account, negatives, geometry, and photometry.'},
    {id:'mc-ipaco',type:'analysis',date:'APR 2013',title:'IPACO photographic analysis',source:'Private technical report',note:'Later analysis argues for a nearby model hypothesis. Rights permit only an authored summary here.'}]},
  {id:'tremonton',year:'1952',place:'Tremonton, Utah',title:'Objects on 16 mm film',tag:'FILM · PROVENANCE',level:'Guided',synopsis:'About 1,200 frames of bright objects were filmed from a roadside. Military panels, the Condon study, and later releases revisit the same underlying footage with different copies and context.',question:'When two files show the same film, what changes—and what does not?',records:[
    {id:'tr-film',type:'video',date:'2 JUL 1952',title:'Historical Tremonton film representation',source:'Later published representation, 70.07 s',asset:'assets/tremonton-reference.mp4',note:'A later representation of the historical film, published in 2026. Treat version provenance separately from event content.'},
    {id:'tr-condon',type:'document',date:'1968',title:'Condon Report, Case 49',source:'University of Colorado study; NCAS copy',note:'Records daylight, handheld 16 fps film, about 1,200 frames. Concludes the images are consistent with birds while noting film alone is not conclusive.'},
    {id:'tr-frame',type:'image',date:'2025 UPLOAD',title:'Tremonton film frame',source:'CUFOS article image; NARA relation asserted',note:'A still representation useful for discussing what is lost when motion and generation history are absent.'},
    {id:'tr-balloon',type:'analysis',date:'1950s TEST',title:'Blue Book balloon comparison',source:'CUFOS article reproduction',note:'A comparison test is evidence about a hypothesis, not an independent observation of the 1952 event.'}]},
  {id:'socorro',year:'1964',place:'Socorro, New Mexico',title:'The Zamora landing report',tag:'REPORTS · SITE',level:'Guided',synopsis:'A police officer reported a close encounter near Socorro. Blue Book and FBI files, scene material, a range schedule, and later hoax claims allow dates, locations, and retellings to be tested.',question:'Do later explanations match the dates and locations in contemporary records?',records:[
    {id:'so-bluebook',type:'document',date:'24 APR 1964',title:'Project Blue Book case file',source:'NARA-roll scan mirror',note:'A 167-page mixed compilation. Federal pages are likely public domain; clippings and private materials are not assumed reusable.'},
    {id:'so-fbi',type:'document',date:'1964',title:'FBI FOIA records',source:'FOIA-file mirror',note:'Twelve scanned pages; completeness of the mirror is not authenticated by public availability.'},
    {id:'so-range',type:'image',date:'24 APR 1964',title:'White Sands daily range schedule',source:'Later published schedule image',note:'A dated schedule can test whether a proposed range activity fits the reported day.'},
    {id:'so-site',type:'image',date:'LATER COPY',title:'Marked landing-site image',source:'NICAP web reproduction',asset:'assets/socorro-site.jpg',note:'A later annotated aerial image; annotation date and authorship are uncertain.'}]},
  {id:'michigan',year:'1966',place:'Dexter & Hillsdale, Michigan',title:'Two nights, one label',tag:'TIMELINE · POLICY',level:'Open',synopsis:'Reports from separate nights and places were gathered under the phrase “swamp gas.” Police accounts, witness drawings, press coverage, congressional papers, and later interviews record both events and their public handling.',question:'Which records concern the sightings, and which concern the institutional response?',records:[
    {id:'mi-ford',type:'document',date:'MAR–OCT 1966',title:'Gerald Ford congressional papers',source:'Congressional correspondence collection',note:'Documents the political request for a hearing and subsequent correspondence.'},
    {id:'mi-hearing',type:'document',date:'5 APR 1966',title:'House Armed Services hearing',source:'GovInfo hearing record',note:'A federal hearing record about UAP investigation policy after the Michigan reports.'},
    {id:'mi-drawings',type:'image',date:'MAR 1966',title:'Project Blue Book witness drawings',source:'Later web reproduction',note:'Drawings attributed to witnesses; the reproduction is not the same as viewing original sheets.'},
    {id:'mi-interview',type:'audio',date:'2017',title:'Harry Willnus retrospective interview',source:'Michigan Public audio',note:'A witness account recorded five decades later. Temporal distance matters when weighing detail.'}]},
  {id:'rendlesham',year:'1980',place:'Rendlesham Forest, Suffolk',title:'Lights beyond the gate',tag:'AUDIO · CHRONOLOGY',level:'Open',synopsis:'A contemporary memorandum, field recording, police response, witness statements, later affidavits, and optical analyses form a long chain in which claims change over time.',question:'Which details appear in contemporary records, and which arrive decades later?',records:[
    {id:'re-tape',type:'audio',date:'28 DEC 1980',title:'Halt field recording',source:'Ian Ridpath-hosted M4A copy',note:'An 18-minute field recording. Timing and spoken observations can be compared with later summaries.'},
    {id:'re-memo',type:'image',date:'13 JAN 1981',title:'“Unexplained Lights” memorandum',source:'UK National Archives image',asset:'assets/rendlesham-memo.jpg',note:'A memorandum written weeks after the events; concise and materially different from some later accounts.'},
    {id:'re-police',type:'document',date:'1980–1999',title:'Suffolk Constabulary UFO file',source:'FOIA mirror scan',note:'Seven pages concerning the police response and later correspondence.'},
    {id:'re-affidavit',type:'document',date:'17 JUN 2010',title:'Charles Halt affidavit',source:'Later affidavit copy',note:'A statement produced nearly thirty years after the event; compare claim chronology before merging details.'}]},
  {id:'jal',year:'1986',place:'Over Alaska',title:'Japan Air Lines 1628',tag:'RADAR · TESTIMONY',level:'Open',synopsis:'Crew reports, air-traffic communications, controller statements, retained radar data, regenerated displays, and later analyses distinguish what was seen live from what was found in replay.',question:'Are visual observations, controller displays, and retained radar returns equivalent evidence?',records:[
    {id:'ja-report',type:'document',date:'NOV 1986',title:'FAA occurrence report',source:'NARA RG 237, catalog 733667',note:'Three-page FAA occurrence/report form for JAL 1628.'},
    {id:'ja-atc',type:'document',date:'18 NOV UTC',title:'FAA ATC transcript',source:'NARA RG 237, 24 pages',note:'Communications transcript; separates what the crew said at the time from later interviews.'},
    {id:'ja-radar',type:'document',date:'1986',title:'Uncorrelated Radar Signals memo',source:'FAA retained-data analysis',note:'Four-page memorandum analyzing retained radar data rather than the live controller display.'},
    {id:'ja-interviews',type:'document',date:'JAN 1987',title:'FAA crew interviews',source:'NARA RG 237',note:'Separate interviews with captain, first officer, and flight engineer recorded after the event.'}]},
  {id:'aguadilla',year:'2013',place:'Aguadilla, Puerto Rico',title:'Object in the infrared',tag:'IR · MOTION',level:'Fieldwork',synopsis:'A CBP infrared recording, official provenance, an AARO reconstruction, airport weather observations, and competing civilian analyses disagree over speed, separation, and apparent contact with water.',question:'How much of the apparent motion belongs to the object, the aircraft, or the sensor view?',records:[
    {id:'ag-video',type:'video',date:'26 APR 2013',title:'CBP infrared video — record 9',source:'CBP FOIA collection; 234.50 s AVI',note:'Officially released infrared footage. A short local AARO reconstruction excerpt is shown to limit redistribution.',asset:'assets/aguadilla-reconstruction.m4v'},
    {id:'ag-provenance',type:'document',date:'29 AUG 2023',title:'CBP UAP FOIA collection page',source:'U.S. Customs and Border Protection',note:'Authenticates CBP publication and links the released video to a larger 389-page records package. Publication authenticates provenance, not an explanation.'},
    {id:'ag-aaro',type:'document',date:'20 MAR 2025',title:'AARO Puerto Rico case resolution',source:'AARO, U.S. Department of Defense',note:'Assesses 8 mph object motion, 656 ft altitude, motion parallax, two nearby objects, and no transmedium behavior; sky lantern attribution has moderate confidence.'},
    {id:'ag-weather',type:'data',date:'25–26 APR 2013',title:'TJBQ ASOS/METAR observations',source:'Iowa Environmental Mesonet redistribution',note:'Hourly airport observations. The bundled extract ends at 26 April 23:50 UTC, 1h32m before the 27 April 01:22 UTC event, so it has no post-event observation and cannot bracket the event.'},
    {id:'ag-scu',type:'analysis',date:'AUG 2015',title:'SCU Aguadilla report',source:'Scientific Coalition for Ufology',note:'Civilian analysis argues for unusual speed and transmedium behavior. Copyright status is unclear; only a short authored summary is included.'},
    {id:'ag-lianza',type:'analysis',date:'4 JUL 2017',title:'Lianza / IPACO lantern analysis',source:'Rubén Lianza / IPACO',note:'Argues for two wind-driven heart-shaped sky lanterns and emphasizes aircraft motion, viewing geometry, and a 7-knot METAR.'},
    {id:'ag-rebuttal',type:'analysis',date:'21 JUL 2017',title:'SCU response to lantern hypothesis',source:'Scientific Coalition for Ufology',note:'Challenges required drift speed, earlier separation visibility, and thermal-contrast explanations for apparent water entry.'}]},
  {id:'gimbal',year:'2015',place:'U.S. East Coast training area',title:'Rotation in the glare',tag:'SENSOR · TRAJECTORY',level:'Open',synopsis:'Official infrared video, release records, later witness accounts, sensor-glare analysis, trajectory reconstructions, and code invite separate tests of image rotation and target motion.',question:'Does rotation in the image require the observed object itself to rotate?',records:[
    {id:'gi-video',type:'video',date:'JAN 2015',title:'GIMBAL — UAP',source:'DVIDS / Naval Air Systems Command',note:'34.47-second official distribution video, posted to DVIDS in 2025 and public-domain-labelled with restrictions.'},
    {id:'gi-foia',type:'document',date:'2021–2025',title:'FOIA 20-F-1095 communications',source:'OSD; mirror copy',note:'Responsive communications about release and handling, not a second observation of the event.'},
    {id:'gi-brief',type:'document',date:'6 APR 2022',title:'F/A-18 pilot brief FOIA release',source:'Department of the Navy; mirror',note:'A later briefing discussing a 2015 detection event; preserve the gap between event and statement.'},
    {id:'gi-path',type:'analysis',date:'2023',title:'Potential flight-path reconstruction',source:'Peings & von Rennenkampff, arXiv/AIAA',note:'Models possible trajectories; results depend on assumptions and should be compared with alternative sensor analyses.'}]}
];

const METHODS=[
 {id:'provenance',title:'Provenance before interpretation',text:'Separate who published a file, who created its underlying content, when each happened, and whether a later copy adds information.'},
 {id:'parallax',title:'Relative motion & parallax',text:'Track observer position, sensor line of sight, zoom, and target assumptions before inferring ground speed from screen motion.'},
 {id:'time',title:'Exact-time coverage',text:'A nearby observation can bracket conditions without measuring the exact minute, altitude, or position of an event.'},
 {id:'corroboration',title:'Independent corroboration',text:'A new encode, crop, or release of the same film improves access or provenance but does not create another independent observation.'}
];

const RELEASE={recordId:'DOW-UAP-PR159',releaseId:'release_06',title:'DOW-UAP-PR159, Historical Film of Reported UFOs, Utah, 1952',publisher:'DoW',incidentDate:'7/2/52',location:'Tremonton, Utah',file:'DOW-UAP-PR159__DOD_111985807.mp4',format:'mp4',size:'79,823,577 bytes',duration:'70.083333 s',dimensions:'1920 × 1080',sha256:'eb01892cf7f9338617e3bb875af742ad71f894823206cbcd448ae2980677def1',dvids:'1023402',asset:'assets/pr159-tremonton.mp4'};
